### ISSUE TITLE
Missing ldap_connect

### ISSUE THREAD

**Issue by rgarrigue** [matomo-org/plugin-LoginLdap#175]
Hi

With an up to date matomo & ldap plugin, 

```
root@staging-matomo:/var/log/matomo# /usr/share/matomo/console loginldap:synchronize-users
Uncaught exception: Call to undefined function Piwik\Plugins\LoginLdap\Ldap\ldap_connect()
in /usr/share/matomo/plugins/LoginLdap/Ldap/Client.php line 80
#0 /usr/share/matomo/plugins/LoginLdap/Model/LdapUsers.php(542): Piwik\Plugins\LoginLdap\Ldap\Client->connect('ldaps://ldap.co...', 636, 15)
#1 /usr/share/matomo/plugins/LoginLdap/Model/LdapUsers.php(501): Piwik\Plugins\LoginLdap\Model\LdapUsers->makeLdapClient()
#2 /usr/share/matomo/plugins/LoginLdap/Model/LdapUsers.php(325): Piwik\Plugins\LoginLdap\Model\LdapUsers->doWithClient(Object(Closure))
#3 /usr/share/matomo/plugins/LoginLdap/Commands/SynchronizeUsers.php(66): Piwik\Plugins\LoginLdap\Model\LdapUsers->getAllUserLogins()
#4 /usr/share/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\LoginLdap\Commands\SynchronizeUsers->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /usr/share/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /usr/share/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\LoginLdap\Commands\SynchronizeUsers), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /usr/share/matomo/core/Console.php(90): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /usr/share/matomo/core/Access.php(626): Piwik\Console->Piwik\{closure}()
#10 /usr/share/matomo/core/Console.php(91): Piwik\Access::doAsSuperUser(Object(Closure))
#11 /usr/share/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /usr/share/matomo/console(27): Symfony\Component\Console\Application->run()
#13 {main}
```

There's dependency about ldap in your `composer.json`, shoudln't there be something like ldap or sympfony-ldap or whatever ?

Best regards,

**Comment by AltamashShaikh** [comment]
Seems like `php-ldap` module is missing, should be fixed by installing the required module
